### ISSUE TITLE
renaming conftest.py

### ISSUE THREAD

**Issue by tarique-msci** [danielbeach/unitTestPySpark#1]
Renaming conftest,py to sparkconfigtest.py or anything similar causes the code to fail. I get the error, fixture 'spark_session' not found. I'm not sure why.

**Comment by danielbeach** [comment]
@tarique-msci the `conftest.py` file is a feature of `pytest` module. https://docs.pytest.org/en/6.2.x/fixture.html , changing the name of that file causes the fixtures not be loaded, and the the `conftest.py` file in this repo defines `spark_session`, so then it becomes unknown because that fixture was not loaded.
